GET http://localhost:8080/api/cart

###

POST http://localhost:8080/api/cart
content-type: application/json

{
  "items": [
    {
      "productId": "ab123",
      "quantity": 1,
      "priceEachInDollars": 11.11
    },
    {
      "productId": "xy234",
      "quantity": 5,
      "priceEachInDollars": 1.66
    }
  ]
}