GET http://localhost:8080/
userid: brian

###

POST http://localhost:8080/
content-type: application/json
userid: brian

{
  "items": [
    {
      "productId": "ab123",
      "quantity": 1,
      "priceEachInDollars": 11.11
    },
    {
      "productId": "xy234",
      "quantity": 5,
      "priceEachInDollars": 1.66
    }
  ]
}