jwt:
  CookieName: "beast-cart"
  SecretKey: "beastCartSecretKeybeastCartSecretKeybeastCartSecretKeybeastCartSecretKeybeastCartSecretKeybeastCartSecretKeybeastCartSecretKeybeastCartSecretKeybeastCartSecretKeybeastCartSecretKeybeastCartSecretKeybeastCartSecretKeybeastCartSecretKeybeastCartSecretKeybeastCartSecretKeybeastCartSecretKeybeastCartSecretKeybeastCartSecretKeybeastCartSecretKeybeastCartSecretKeybeastCartSecretKeybeastCartSecretKeybeastCartSecretKeybeastCartSecretKey"
  ExpirationMs: 86400000
